### ISSUE TITLE
Required field validation does not work properly with class-based components

### ISSUE THREAD

**Issue by lamontadams** [tkrotoff/react-form-with-constraints#38]
Hey there,

Using the `react-form-with-constraints-material-ui` npm package, I followed [the MaterialUI example](https://codesandbox.io/s/github/tkrotoff/react-form-with-constraints/tree/master/examples/MaterialUI) - which seems to work fine in the codesandbox - to try and get form validation working inside a class-based component.

After a couple of hours working on a simple two `TextField` login form (both TextFields carry both `required` and `inputProps={{required:true}}`), I'm giving up. I see the HTML attributes being applied to the elements inside the form, but `FormWithConstraints.isValid()` is always true, and `Field.isValid()` returns true for every field on the form even when both fields are empty and untouched.

I tossed up a CodeSandbox repro [here](https://codesandbox.io/s/9yn3l30rnp) - check the console with the submit button is pressed.

I also ran across [a variant](https://codepen.io/tkrotoff/pen/BRGdqL) sample that is component based, and that wraps the ref assignment up into an arrow function. I tried that approach too, but it doesn't seem to make any difference in what I'm seeing, the form is always valid when it shouldn't be.

Does the library just not work with class-based components or am I doing something wrong?

Thanks.

**Comment by tkrotoff** [comment]
Here your CodeSandbox fixed: https://codesandbox.io/s/0xvj8qo5o0

You can retrieve the Material UI example with React classes instead of hooks here: https://github.com/tkrotoff/react-form-with-constraints/blob/v0.11.0/examples/MaterialUI/App.tsx (v0.11 instead of v0.12).

Several mistakes:

- Required: use `FieldFeedbacks` (with a valid `for` attribute) and `FieldFeedback` otherwise fields won't be checked (the library does not know which fields to check)

```JS
<FieldFeedbacks for="emailAddress">
  <FieldFeedback when="*" />
</FieldFeedbacks>
```

- Optional (without you won't get a nice looking UI): import `TextField` from `react-form-with-constraints-material-ui` instead of `@material-ui`

You can "debug" and see what happens by using `DisplayFields` from `react-form-with-constraints-tools`.

**Comment by lamontadams** [comment]
:+1:  I figured I was missing something blindingly obvious. Thanks!
